-- ==============================================================================
-- PROJECT: Sales & Customer Analytics Warehouse
-- FILE: 07_customer_analysis.sql
-- DESCRIPTION: Behavioral Analytics, Churn Prediction & Repeat Purchase Rate
-- AUTHOR: Student (Placement Portfolio Project)
-- ==============================================================================

-- ==============================================================================
-- 1. NEW VS RETURNING CUSTOMER REVENUE SHARE BY MONTH
-- Tracks revenue generated by first-time buyers vs repeat customers
-- ==============================================================================
WITH customer_first_orders AS (
    SELECT 
        customer_id,
        MIN(order_id) AS first_order_id
    FROM orders
    WHERE order_status = 'Completed'
    GROUP BY customer_id
)
SELECT 
    TO_CHAR(o.order_date, 'YYYY-MM') AS sales_month,
    COUNT(DISTINCT CASE WHEN cfo.first_order_id IS NOT NULL THEN o.customer_id END) AS new_customers,
    COUNT(DISTINCT CASE WHEN cfo.first_order_id IS NULL THEN o.customer_id END) AS returning_customers,
    ROUND(SUM(CASE WHEN cfo.first_order_id IS NOT NULL THEN o.total_amount ELSE 0 END)::numeric, 2) AS new_customer_revenue,
    ROUND(SUM(CASE WHEN cfo.first_order_id IS NULL THEN o.total_amount ELSE 0 END)::numeric, 2) AS returning_customer_revenue,
    ROUND((SUM(CASE WHEN cfo.first_order_id IS NULL THEN o.total_amount ELSE 0 END) * 100.0 / NULLIF(SUM(o.total_amount), 0))::numeric, 2) AS returning_revenue_share_pct
FROM orders o
LEFT JOIN customer_first_orders cfo ON o.order_id = cfo.first_order_id
WHERE o.order_status = 'Completed'
GROUP BY TO_CHAR(o.order_date, 'YYYY-MM')
ORDER BY sales_month;


-- ==============================================================================
-- 2. REPEAT PURCHASE RATE & ORDER FREQUENCY DISTRIBUTION
-- Quantifies customer loyalty: % of customers who purchase more than once
-- ==============================================================================
WITH customer_order_counts AS (
    SELECT 
        customer_id,
        COUNT(order_id) AS total_orders,
        SUM(total_amount) AS total_spend
    FROM orders
    WHERE order_status = 'Completed'
    GROUP BY customer_id
)
SELECT 
    COUNT(customer_id) AS total_active_customers,
    COUNT(CASE WHEN total_orders > 1 THEN 1 END) AS repeat_customers,
    COUNT(CASE WHEN total_orders = 1 THEN 1 END) AS one_time_customers,
    ROUND((COUNT(CASE WHEN total_orders > 1 THEN 1 END) * 100.0 / COUNT(customer_id))::numeric, 2) AS repeat_purchase_rate_pct,
    ROUND(AVG(total_orders)::numeric, 2) AS avg_orders_per_customer
FROM customer_order_counts;


-- ==============================================================================
-- 3. CUSTOMER CHURN RISK DETECTION (Inactive for > 90 Days with High Prior Value)
-- Identifies top high-value customers showing signs of inactivity
-- ==============================================================================
WITH max_date_cte AS (
    SELECT MAX(order_date) AS max_order_date FROM orders
),
customer_activity AS (
    SELECT 
        c.customer_id,
        c.first_name || ' ' || c.last_name AS customer_name,
        c.email,
        r.region_name,
        MAX(o.order_date) AS last_order_date,
        COUNT(o.order_id) AS total_completed_orders,
        SUM(o.total_amount) AS lifetime_spend,
        EXTRACT(EPOCH FROM ((SELECT max_order_date FROM max_date_cte) - MAX(o.order_date)))/86400 AS days_inactive
    FROM customers c
    JOIN orders o ON c.customer_id = o.customer_id
    JOIN regions r ON c.region_id = r.region_id
    WHERE o.order_status = 'Completed'
    GROUP BY c.customer_id, customer_name, c.email, r.region_name
)
SELECT 
    customer_id,
    customer_name,
    email,
    region_name,
    last_order_date::date,
    total_completed_orders,
    ROUND(lifetime_spend::numeric, 2) AS lifetime_spend,
    ROUND(days_inactive::numeric, 0) AS days_inactive,
    CASE 
        WHEN days_inactive > 180 THEN 'High Churn Risk'
        WHEN days_inactive BETWEEN 90 AND 180 THEN 'Medium Churn Risk'
        ELSE 'Active'
    END AS churn_risk_status
FROM customer_activity
WHERE days_inactive >= 90 AND lifetime_spend > 500
ORDER BY lifetime_spend DESC
LIMIT 25;


-- ==============================================================================
-- 4. SPENDING GROWTH DETECTION (Customers with 3 Consecutive Increasing Orders)
-- Identifies expanding high-value customer relationships
-- ==============================================================================
WITH customer_order_seq AS (
    SELECT 
        customer_id,
        order_id,
        order_date,
        total_amount AS current_amount,
        LAG(total_amount, 1) OVER (PARTITION BY customer_id ORDER BY order_date) AS prev_amount_1,
        LAG(total_amount, 2) OVER (PARTITION BY customer_id ORDER BY order_date) AS prev_amount_2
    FROM orders
    WHERE order_status = 'Completed'
)
SELECT 
    c.customer_id,
    c.first_name || ' ' || c.last_name AS customer_name,
    cos.order_id,
    cos.order_date::date,
    ROUND(cos.prev_amount_2::numeric, 2) AS order_val_1,
    ROUND(cos.prev_amount_1::numeric, 2) AS order_val_2,
    ROUND(cos.current_amount::numeric, 2) AS order_val_3
FROM customer_order_seq cos
JOIN customers c ON cos.customer_id = c.customer_id
WHERE cos.prev_amount_2 IS NOT NULL
  AND cos.prev_amount_1 > cos.prev_amount_2
  AND cos.current_amount > cos.prev_amount_1
ORDER BY cos.current_amount DESC
LIMIT 20;
